spring:
  datasource:
    url: jdbc:h2:file:./data/auth_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # update는 기존의 데이터를 유지하고 수정만 하고, create는 새로 만듦
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console